
services:
  db:
    image: postgres:15
    container_name: silo_db_prod
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: silo_redis_prod
    restart: always
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data

  web:
    image: aswindevpk/silo-web:latest
    container_name: silo_web_prod
    restart: always
    command: gunicorn --access-logfile - -k uvicorn.workers.UvicornWorker --workers 2 --bind 0.0.0.0:8000 config.asgi:application
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    ports:
      - "127.0.0.1:8000:8000"
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1

  celery:
    image: aswindevpk/silo-web:latest
    container_name: silo_celery_prod
    restart: always
    command: celery -A config worker --loglevel=INFO 
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1

volumes:
  postgres_data:
  redis_data:
  static_volume:
  media_volume:
