# Generated by Django 6.0.6 on 2026-07-25 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customuser_default_workspace'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='default_workspace',
        ),
    ]
