# Generated by Django 6.0.6 on 2026-08-04 18:02

import apps.workspaces.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0003_plan_remove_workspace_created_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='workspaceinvitation',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='workspaceinvitation',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REVOKED', 'Revoked')], default='PENDING', max_length=10),
        ),
        migrations.AlterField(
            model_name='workspaceinvitation',
            name='email',
            field=models.EmailField(db_index=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='workspaceinvitation',
            name='expires_at',
            field=models.DateTimeField(default=apps.workspaces.models.default_invitation_expiry),
        ),
        migrations.AddIndex(
            model_name='workspaceinvitation',
            index=models.Index(fields=['token', 'status'], name='workspaces__token_bd9df9_idx'),
        ),
        migrations.AddConstraint(
            model_name='workspaceinvitation',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'PENDING')), fields=('workspace', 'email'), name='unique_pending_invitation_per_workspace'),
        ),
        migrations.RemoveField(
            model_name='workspaceinvitation',
            name='is_accepted',
        ),
    ]
