# Generated by Django 6.0.6 on 2026-08-04 19:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0004_alter_workspaceinvitation_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='workspaceinvitation',
            name='workspaces__token_bd9df9_idx',
        ),
        migrations.RemoveConstraint(
            model_name='workspaceinvitation',
            name='unique_pending_invitation_per_workspace',
        ),
        migrations.AlterUniqueTogether(
            name='workspacemember',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='workspacemember',
            name='email',
            field=models.EmailField(blank=True, db_index=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='workspacemember',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workspacemember',
            name='invited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_invitations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workspacemember',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ACTIVE', 'Active'), ('REVOKED', 'Revoked')], default='ACTIVE', max_length=10),
        ),
        migrations.AddField(
            model_name='workspacemember',
            name='token',
            field=models.UUIDField(blank=True, editable=False, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='workspacemember',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workspace_memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='workspacemember',
            index=models.Index(fields=['token', 'status'], name='workspaces__token_afeb24_idx'),
        ),
        migrations.AddConstraint(
            model_name='workspacemember',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'PENDING')), fields=('workspace', 'email'), name='unique_pending_invitation_per_workspace'),
        ),
        migrations.AddConstraint(
            model_name='workspacemember',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('workspace', 'user'), name='unique_workspace_user'),
        ),
        migrations.RemoveField(
            model_name='workspacemember',
            name='is_active',
        ),
        migrations.DeleteModel(
            name='WorkspaceInvitation',
        ),
    ]
